### ISSUE TITLE
Add aarch64 release binaries

### ISSUE THREAD

**Issue by benfleis** [babashka/pod-babashka-fswatcher#17]
arm binaries are built for linux, would be nice to have them for mac as well to avoid dependency on rosetta.

see also https://github.com/babashka/pod-babashka-fswatcher/releases/tag/v0.0.4

**Comment by borkdude** [comment]
@lispyclouds Maybe this is also one to add?

**Comment by borkdude** [comment]
For the next release I mean

**Comment by lispyclouds** [comment]
Closed in https://github.com/babashka/pod-babashka-fswatcher/commit/19e2025e0e88d752a6e561906b41a9d20c8319f7
