### ISSUE TITLE
Add test

### ISSUE THREAD

**Issue by borkdude** [babashka/pod-babashka-fswatcher#5]
@lispyclouds The script in `test/script.clj` is now a proper runnable babashka test script. It returns a non-zero exit code when the compiled pod doesn't work correctly. Maybe we can hook this up as a test in CI and run it with babashka.

**Comment by lispyclouds** [comment]
Closed by https://github.com/babashka/pod-babashka-fswatcher/commit/dac58c12a66f3131e70ee914a5c0b3220fc3dc3b
